### PR TITLE
Add Flask-WTF dependencies

### LINKED ISSUE #37: SQLAlchemy provider uses FlaskForm from Flask-WTF which is not a dependency
A minor packaging issue I noticed while trying to clean up unused deps; `flask_multipass.providers.sqlalchemy` pulls `FlaskForm` from `flask_multipass._compat` which pulls it from `flask_wtf` which is not listed as a dependency of `Flask-Multipass`.

Choices for correction would appear to be listing `Flask-WTF` as a dependency of `Flask-Multipass[sqlalchemy]`, or reworking `flask_multipass._compat` to reference `wtforms.form.Form` instead.

### PR DESCRIPTION
**Pull request by arrdem**
The SQLAlchemy and LDAP backends both rely on Flask-WTF for various forms, but this dependency had not been previously listed.

Fixes #37

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Thanks! Just in case you didn't notice: You committed with an email address that is not linked to your GitHub account.

**Comment by arrdem** [comment]
Just got that fixed too ;) new project woes.

**Comment by ThiefMaster** [comment]
CI failure might be unrelated, but if you want to have a look what's going wrong there feel free to go ahead

**Comment by arrdem** [comment]
Yeah poking at this some locally this seems to be a `Flask` latest release vs latest commit difference, and the failure is actually over in werkzeug so presumably it'll have to get ironed out before any releases.

**Comment by arrdem** [comment]
Using latest Flask and Werkzeug together builds cleanly and makes sense since their development is paired anyway.

**Review by ThiefMaster — APPROVED** [review]

**Pull request merged**
